<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    /**
     * Seed roles and permissions for the SPMI workflow.
     */
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $permissions = [
            'dashboard.view',
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'users.impersonate',
            'roles.view',
            'roles.create',
            'roles.update',
            'roles.delete',
            'units.view',
            'units.create',
            'units.update',
            'units.delete',
            'spmi-periods.view',
            'spmi-periods.create',
            'spmi-periods.update',
            'spmi-periods.delete',
            'standard-categories.view',
            'standard-categories.create',
            'standard-categories.update',
            'standard-categories.delete',
            'quality-standards.view',
            'quality-standards.create',
            'quality-standards.update',
            'quality-standards.submit',
            'quality-standards.approve',
            'quality-standards.delete',
            'standard-indicators.view',
            'standard-indicators.create',
            'standard-indicators.update',
            'standard-indicators.delete',
            'indicator-assignments.view',
            'indicator-assignments.create',
            'indicator-assignments.update',
            'indicator-assignments.delete',
            'indicator-achievements.view',
            'indicator-achievements.create',
            'indicator-achievements.update',
            'indicator-achievements.submit',
            'indicator-achievements.review',
            'achievement-evidences.view',
            'achievement-evidences.create',
            'achievement-evidences.delete',
            'ami-periods.view',
            'ami-periods.create',
            'ami-periods.update',
            'ami-periods.delete',
            'ami-audits.view',
            'ami-audits.create',
            'ami-audits.update',
            'ami-audits.finalize',
            'ami-checklists.view',
            'ami-checklists.create',
            'ami-checklists.update',
            'ami-findings.view',
            'ami-findings.create',
            'ami-findings.update',
            'corrective-actions.view',
            'corrective-actions.create',
            'corrective-actions.update',
            'corrective-actions.submit',
            'corrective-actions.review',
            'corrective-action-evidences.view',
            'corrective-action-evidences.create',
            'corrective-action-evidences.delete',
            'quality-documents.view',
            'quality-documents.create',
            'quality-documents.update',
            'quality-documents.approve',
            'quality-documents.delete',
            'activity-logs.view',
            'reports.view',
            'reports.export',
            'notifications.view',
            'notifications.update',
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate([
                'name' => $permission,
                'guard_name' => 'web',
            ]);
        }

        $permissionGroups = [
            'master' => [
                'dashboard.view',
                'units.view',
                'spmi-periods.view',
                'standard-categories.view',
                'quality-standards.view',
                'standard-indicators.view',
                'quality-documents.view',
                'reports.view',
            ],
            'spmi_admin' => [
                'units.create',
                'units.update',
                'spmi-periods.create',
                'spmi-periods.update',
                'standard-categories.create',
                'standard-categories.update',
                'quality-standards.create',
                'quality-standards.update',
                'quality-standards.submit',
                'quality-standards.approve',
                'standard-indicators.create',
                'standard-indicators.update',
                'indicator-assignments.view',
                'indicator-assignments.create',
                'indicator-assignments.update',
                'indicator-achievements.view',
                'indicator-achievements.review',
                'achievement-evidences.view',
                'quality-documents.create',
                'quality-documents.update',
                'quality-documents.approve',
                'reports.export',
                'notifications.view',
                'notifications.update',
            ],
            'ami_admin' => [
                'ami-periods.view',
                'ami-periods.create',
                'ami-periods.update',
                'ami-audits.view',
                'ami-audits.create',
                'ami-audits.update',
                'ami-audits.finalize',
                'ami-checklists.view',
                'ami-checklists.create',
                'ami-checklists.update',
                'ami-findings.view',
                'ami-findings.create',
                'ami-findings.update',
                'corrective-actions.view',
                'corrective-actions.review',
                'corrective-action-evidences.view',
            ],
            'unit_work' => [
                'indicator-achievements.view',
                'indicator-achievements.create',
                'indicator-achievements.update',
                'indicator-achievements.submit',
                'achievement-evidences.view',
                'achievement-evidences.create',
                'achievement-evidences.delete',
                'corrective-actions.view',
                'corrective-actions.create',
                'corrective-actions.update',
                'corrective-actions.submit',
                'corrective-action-evidences.view',
                'corrective-action-evidences.create',
                'corrective-action-evidences.delete',
                'notifications.view',
                'notifications.update',
            ],
        ];

        $roles = [
            'super_admin' => $permissions,
            'admin_lpm' => array_values(array_unique([
                ...$permissionGroups['master'],
                ...$permissionGroups['spmi_admin'],
                ...$permissionGroups['ami_admin'],
                'users.view',
                'users.create',
                'users.update',
                'roles.view',
                'activity-logs.view',
            ])),
            'pimpinan' => [
                'dashboard.view',
                'units.view',
                'spmi-periods.view',
                'standard-categories.view',
                'quality-standards.view',
                'quality-standards.approve',
                'standard-indicators.view',
                'indicator-achievements.view',
                'achievement-evidences.view',
                'ami-periods.view',
                'ami-audits.view',
                'ami-findings.view',
                'corrective-actions.view',
                'quality-documents.view',
                'quality-documents.approve',
                'reports.view',
                'reports.export',
                'notifications.view',
                'notifications.update',
            ],
            'unit_pic' => array_values(array_unique([
                ...$permissionGroups['master'],
                ...$permissionGroups['unit_work'],
                'indicator-assignments.view',
                'ami-audits.view',
                'ami-checklists.view',
                'ami-findings.view',
            ])),
            'auditor' => [
                'dashboard.view',
                'units.view',
                'quality-standards.view',
                'standard-indicators.view',
                'indicator-achievements.view',
                'achievement-evidences.view',
                'ami-periods.view',
                'ami-audits.view',
                'ami-checklists.view',
                'ami-checklists.create',
                'ami-checklists.update',
                'ami-findings.view',
                'ami-findings.create',
                'ami-findings.update',
                'corrective-actions.view',
                'corrective-actions.review',
                'corrective-action-evidences.view',
                'quality-documents.view',
                'reports.view',
                'notifications.view',
                'notifications.update',
            ],
            'viewer' => [
                'dashboard.view',
                'units.view',
                'spmi-periods.view',
                'standard-categories.view',
                'quality-standards.view',
                'standard-indicators.view',
                'indicator-achievements.view',
                'achievement-evidences.view',
                'ami-periods.view',
                'ami-audits.view',
                'ami-findings.view',
                'corrective-actions.view',
                'quality-documents.view',
                'reports.view',
                'notifications.view',
            ],
        ];

        foreach ($roles as $roleName => $rolePermissions) {
            $role = Role::firstOrCreate([
                'name' => $roleName,
                'guard_name' => 'web',
            ]);

            $role->syncPermissions($rolePermissions);
        }

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
